### ISSUE TITLE
user authentication problems

### ISSUE THREAD

**Issue by jenong-140** [CharlesShi12/RecommendationSystems#1]
hey bro, i need some help here. i was new with this and have some problem while running the program, would u like to help solve this kinda thing :) thanks

the output problems : 
User authentication requires interaction with your web browser. Once you enter your credentials and give authorization, you will be redirected to a url.  Paste that url you were directed to to complete the authorization.
Opened https://accounts.spotify.com/authorize?client_id=976e7562af854c879c56c7ab98b207ec&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8886%2Fcallback&scope=playlist-read-private in your browser

**Comment by CharlesShi12** [comment]
You will have to use your own Spotify credentials for your ID and Token. These credentials are accessible after you create a Spotify developer account.
